export enum RolesPermissions {
  EDIT_PERMISSION = "EDIT_PERMISSION",
  CREATE_PERMISSION = "CREATE_PERMISSION",
  DELETE_PERMISSION = "DELETE_PERMISSION",
  READ_PERMISSION = "READ_PERMISSION",
}

export enum Roles {
  ADMIN = "ADMIN",
  TEACHER = "TEACHER",
  STUDENT = "STUDENT",
  COLABORATOR = "COLABORATOR",
}
